# Generated by Django 4.2.7 on 2024-04-09 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import referralAPI.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(default=referralAPI.utils._generate_ID_, max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('referral_code', models.CharField(max_length=4, null=True)),
                ('referral_score', models.IntegerField(default=0)),
                ('registered_time', models.CharField(default=1712677095.716495, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=referralAPI.utils._getToken_, max_length=15)),
                ('last_login_time', models.DateTimeField(default=datetime.datetime(2024, 4, 9, 21, 8, 15, 717496))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referralAPI.user')),
            ],
        ),
    ]
